event_type:
  class: sfDoctrineRouteCollection
  options:
    model:                EventType
    module:               eventType
    prefix_path:          /eventType
    column:               id
    with_wildcard_routes: true

city:
  class: sfDoctrineRouteCollection
  options:
    model:                City
    module:               city
    prefix_path:          /city
    column:               id
    with_wildcard_routes: true

country:
  class: sfDoctrineRouteCollection
  options:
    model:                Country
    module:               country
    prefix_path:          /country
    column:               id
    with_wildcard_routes: true

industry:
  class: sfDoctrineRouteCollection
  options:
    model:                Industry
    module:               industry
    prefix_path:          /industry
    column:               id
    with_wildcard_routes: true

event:
  class: sfDoctrineRouteCollection
  options:
    model:                Event
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: dashboard, action: index }