<?php

/**
 * RegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Region');
    }
    
    // fetch an organiser by shortcode
    public static function getRegionByShortCode($shortCode) 
    {
	// create the queryfilters
	$q = Doctrine_Query::create();
	// select only the bits we need
	$q->from("Region r");	
        // add the filters
	$q->addWhere("r.short_code = ?", $shortCode);
        // get the result
	return $q->fetchOne();		
    }        
}