<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/23 22:47:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=event',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
